version: "3.7"

services:
  server:
    restart: always
    ports:
      - "8000:8000"
    networks:
      - container_net
    build: .
    volumes:
      - .:/app
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - container_net
networks:
  container_net:
    external: true
    name: container_net
volumes:
  pgdata:
