version: "3.7"

services:
  server:
    restart: always
    ports:
      - "8000:8000"
    networks:
      - container_net
    build: .
    volumes:
      - .:/app

networks:
  container_net:
    external: true
    name: container_net
volumes:
  pgdata:
